apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kernel-enhancement
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kernel-enhancement
  template:
    metadata:
      labels:
        name: kernel-enhancement
    spec:
      hostPID: true
      tolerations:
      - operator: "Exists"
      containers:
      - name: kernel-enhancement
        image: amazonlinux:2023
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - |
          set -e

          # Install necessary tools
          dnf install -y wget util-linux systemd dbus

          # Download your script directly into the host's filesystem
          wget -O /host/tmp/upp-customizations.sh https://raw.githubusercontent.com/Financial-Times/eks-files/master/upp-customizations.sh
          chmod +x /host/tmp/upp-customizations.sh

          # Mount necessary filesystems for systemctl to work
          mount --bind /run /host/run
          mount --bind /sys/fs/cgroup /host/sys/fs/cgroup

          # Execute the script on the host using nsenter
          nsenter --target 1 --mount --uts --ipc --net --pid -- /bin/bash -x /tmp/upp-customizations.sh

          # Unmount the bind mounts
          umount /host/run
          umount /host/sys/fs/cgroup


          # Keep the container running
          sleep infinity
        volumeMounts:
        - name: host-root
          mountPath: /host
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory
